name: CD - Build & Push (GHCR)

on:
  pull_request:
    branches: [ main ]   # PR: valida build (sem push)
  push:
    branches: [ main ]   # main: build + push

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # necessário para publicar no GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # Gera o nome da imagem em minúsculas: ghcr.io/<owner>/<repo>
      - name: Compute image name (lowercase)
        id: meta
        run: |
          echo "image=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      # Só loga no GHCR quando for push no main
      - name: Login GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Em PR: build sem push; em push no main: build + push
      - name: Build & (maybe) Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ steps.meta.outputs.image }}:latest
            ${{ steps.meta.outputs.image }}:${{ github.sha }}
