name: CD - Build & Push (GHCR)

on:
  pull_request:
    branches: [ main ]   # PR: valida build (sem push)
  push:
    branches: [ main ]   # main: build + push

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # necessário para publicar no GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # Em push no main: autentica no GHCR usando GITHUB_TOKEN
      - name: Login GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & (maybe) Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          # GHCR exige caminho em minúsculas
          tags: |
            ghcr.io/${{ toLower(github.repository) }}:latest
            ghcr.io/${{ toLower(github.repository) }}:${{ github.sha }}
